name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Inject environment variables into config.js
        run: |
          sed -i "s|__GITHUB_CLIENT_ID__|${{ secrets.GITHUB_CLIENT_ID }}|g" ./config.js
          sed -i "s|__REDIRECT_URI__|${{ secrets.GITHUB_REDIRECT_URI }}|g" ./config.js

      - name: Build with Parcel
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
